### ISSUE TITLE
no app_id on wayland

### ISSUE THREAD

**Issue by deathtrip** [zigalenarcic/mangl#16]
After installing the latest git version from the AUR, i noticed the "app_id" value being empty, which wasn't the case before.
This is a problem for window rules on tiling window managers, and for programs thet rename workspaces based on their app_id.

**Comment by zigalenarcic** [comment]
Hi,
it looks like it is caused by a change in GLFW version 3.4. I only have 3.3, but I added the code which should fix the issue in commit [d9ef669aadb0213e27e68c9c1976863a0a219e58](https://github.com/zigalenarcic/mangl/commit/d9ef669aadb0213e27e68c9c1976863a0a219e58). Can you please check if it works?

**Comment by deathtrip** [comment]
Just compiled it, and it works fine. Thanks for fixing it so quickly.

**Comment by zigalenarcic** [comment]
Great! Thanks for testing.
